security:
    encoders:
        App\Entity\Admin:
            algorithm: bcrypt
    providers:
        users_in_memory: { memory: null }
        auth:
            entity:
                class: App\Entity\Admin
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: true

            provider: auth

            form_login:
                # route ver le form de connexion
                login_path: login
                # ou vont les donnée a la validation
                check_path: login
                # ou on met la redirection
                default_target_path: admin_dashboard
            logout:
                # La route pour logout
                path: logout
                # La redirection
                target: home

        main:
            anonymous: true
            lazy: true
            provider: users_in_memory
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
